opendnp3: opendnp3::ITransactable::End
void opendnp3::ITransactable::End () [inline]
Definition at line 98 of file ITransactable.h.
References _End(), and mInProgress.
Referenced by opendnp3::Transaction::End(), and opendnp3::Transaction::~Transaction().
{
    assert(mInProgress);
    mInProgress = false;
    this->_End();
}