opendnp3: opendnp3::ITransactable::Start
void opendnp3::ITransactable::Start () [inline]
Definition at line 91 of file ITransactable.h.
References _Start(), and mInProgress.
Referenced by opendnp3::Transaction::Start(), and opendnp3::Transaction::Transaction().
{
    this->_Start();
    assert(!mInProgress);
    mInProgress = true;
}