opendnp3: opendnp3::DataPoint::SetQuality
void opendnp3::DataPoint::SetQuality (uint8_t aQuality) [inline, virtual]
Reimplemented in opendnp3::BoolDataPoint.
Definition at line 154 of file BaseDataTypes.h.
References mQuality.
Referenced by opendnp3::Analog::Analog(), opendnp3::Counter::Counter(), and opendnp3::SetpointStatus::SetpointStatus().
{
    mQuality = aQuality;
}