var annotated =
[
    [ "opendnp3::Analog", "dc/dd8/classopendnp3_1_1_analog.html", "dc/dd8/classopendnp3_1_1_analog" ],
    [ "opendnp3::AnalogOutput< T >", "de/d0e/classopendnp3_1_1_analog_output.html", "de/d0e/classopendnp3_1_1_analog_output" ],
    [ "opendnp3::AnalogOutputDouble64", "db/de6/classopendnp3_1_1_analog_output_double64.html", "db/de6/classopendnp3_1_1_analog_output_double64" ],
    [ "opendnp3::AnalogOutputFloat32", "d2/d1b/classopendnp3_1_1_analog_output_float32.html", "d2/d1b/classopendnp3_1_1_analog_output_float32" ],
    [ "opendnp3::AnalogOutputInt16", "d0/d43/classopendnp3_1_1_analog_output_int16.html", "d0/d43/classopendnp3_1_1_analog_output_int16" ],
    [ "opendnp3::AnalogOutputInt32", "de/d53/classopendnp3_1_1_analog_output_int32.html", "de/d53/classopendnp3_1_1_analog_output_int32" ],
    [ "opendnp3::AppConfig", "d6/d44/structopendnp3_1_1_app_config.html", "d6/d44/structopendnp3_1_1_app_config" ],
    [ "opendnp3::ArgumentException", "d5/d04/classopendnp3_1_1_argument_exception.html", "d5/d04/classopendnp3_1_1_argument_exception" ],
    [ "opendnp3::Binary", "db/dcf/classopendnp3_1_1_binary.html", "db/dcf/classopendnp3_1_1_binary" ],
    [ "opendnp3::BitfieldObject", "d2/d89/classopendnp3_1_1_bitfield_object.html", "d2/d89/classopendnp3_1_1_bitfield_object" ],
    [ "opendnp3::BoolDataPoint", "df/dd5/classopendnp3_1_1_bool_data_point.html", "df/dd5/classopendnp3_1_1_bool_data_point" ],
    [ "opendnp3::Change< T >", "dd/d56/structopendnp3_1_1_change.html", "dd/d56/structopendnp3_1_1_change" ],
    [ "opendnp3::ClassMask", "dc/d80/structopendnp3_1_1_class_mask.html", "dc/d80/structopendnp3_1_1_class_mask" ],
    [ "opendnp3::CommandObject< T >", "d4/d59/classopendnp3_1_1_command_object.html", "d4/d59/classopendnp3_1_1_command_object" ],
    [ "opendnp3::CommandResponse", "d1/d11/classopendnp3_1_1_command_response.html", "d1/d11/classopendnp3_1_1_command_response" ],
    [ "opendnp3::ControlRelayOutputBlock", "d4/d3c/classopendnp3_1_1_control_relay_output_block.html", "d4/d3c/classopendnp3_1_1_control_relay_output_block" ],
    [ "opendnp3::ControlStatus", "da/d58/classopendnp3_1_1_control_status.html", "da/d58/classopendnp3_1_1_control_status" ],
    [ "opendnp3::Counter", "de/d83/classopendnp3_1_1_counter.html", "de/d83/classopendnp3_1_1_counter" ],
    [ "opendnp3::DataPoint", "d3/dab/classopendnp3_1_1_data_point.html", "d3/dab/classopendnp3_1_1_data_point" ],
    [ "opendnp3::DeadbandPointRecord", "d5/de5/structopendnp3_1_1_deadband_point_record.html", "d5/de5/structopendnp3_1_1_deadband_point_record" ],
    [ "opendnp3::DestructorHook", "dd/def/classopendnp3_1_1_destructor_hook.html", "dd/def/classopendnp3_1_1_destructor_hook" ],
    [ "opendnp3::DeviceTemplate", "dc/da2/structopendnp3_1_1_device_template.html", "dc/da2/structopendnp3_1_1_device_template" ],
    [ "opendnp3::DNP3Manager", "d5/d3b/classopendnp3_1_1_d_n_p3_manager.html", "d5/d3b/classopendnp3_1_1_d_n_p3_manager" ],
    [ "opendnp3::EventMaxConfig", "d1/dce/structopendnp3_1_1_event_max_config.html", "d1/dce/structopendnp3_1_1_event_max_config" ],
    [ "opendnp3::EventPointRecord", "df/d53/structopendnp3_1_1_event_point_record.html", "df/d53/structopendnp3_1_1_event_point_record" ],
    [ "opendnp3::Exception", "df/d74/classopendnp3_1_1_exception.html", "df/d74/classopendnp3_1_1_exception" ],
    [ "opendnp3::ExceptionScan", "d0/d6f/structopendnp3_1_1_exception_scan.html", "d0/d6f/structopendnp3_1_1_exception_scan" ],
    [ "opendnp3::FilterAssoc", "de/d55/structopendnp3_1_1_filter_assoc.html", "de/d55/structopendnp3_1_1_filter_assoc" ],
    [ "opendnp3::FixedObject", "d5/de7/classopendnp3_1_1_fixed_object.html", "d5/de7/classopendnp3_1_1_fixed_object" ],
    [ "opendnp3::GrpVar", "d0/d84/structopendnp3_1_1_grp_var.html", "d0/d84/structopendnp3_1_1_grp_var" ],
    [ "opendnp3::IChannel", "d0/dbf/classopendnp3_1_1_i_channel.html", "d0/dbf/classopendnp3_1_1_i_channel" ],
    [ "opendnp3::ICommandHandler", "d7/d3e/classopendnp3_1_1_i_command_handler.html", "d7/d3e/classopendnp3_1_1_i_command_handler" ],
    [ "opendnp3::ICommandProcessor", "d8/dc1/classopendnp3_1_1_i_command_processor.html", "d8/dc1/classopendnp3_1_1_i_command_processor" ],
    [ "opendnp3::IDataObserver", "df/d55/classopendnp3_1_1_i_data_observer.html", "df/d55/classopendnp3_1_1_i_data_observer" ],
    [ "opendnp3::ILogBase", "d1/d0b/classopendnp3_1_1_i_log_base.html", "d1/d0b/classopendnp3_1_1_i_log_base" ],
    [ "opendnp3::IMaster", "dd/dd6/classopendnp3_1_1_i_master.html", "dd/dd6/classopendnp3_1_1_i_master" ],
    [ "opendnp3::IndexedObject", "de/d15/classopendnp3_1_1_indexed_object.html", null ],
    [ "opendnp3::IndexOutOfBoundsException", "da/dee/classopendnp3_1_1_index_out_of_bounds_exception.html", "da/dee/classopendnp3_1_1_index_out_of_bounds_exception" ],
    [ "opendnp3::InvalidStateException", "d6/d58/classopendnp3_1_1_invalid_state_exception.html", "d6/d58/classopendnp3_1_1_invalid_state_exception" ],
    [ "opendnp3::IOutstation", "dc/d96/classopendnp3_1_1_i_outstation.html", "dc/d96/classopendnp3_1_1_i_outstation" ],
    [ "opendnp3::IStack", "d0/da7/classopendnp3_1_1_i_stack.html", "d0/da7/classopendnp3_1_1_i_stack" ],
    [ "opendnp3::IStackObserver", "d0/de9/classopendnp3_1_1_i_stack_observer.html", "d0/de9/classopendnp3_1_1_i_stack_observer" ],
    [ "opendnp3::ITransactable", "d0/d64/classopendnp3_1_1_i_transactable.html", "d0/d64/classopendnp3_1_1_i_transactable" ],
    [ "opendnp3::IVtoEndpoint", "dd/d84/classopendnp3_1_1_i_vto_endpoint.html", "dd/d84/classopendnp3_1_1_i_vto_endpoint" ],
    [ "opendnp3::LinkConfig", "dc/dd1/structopendnp3_1_1_link_config.html", "dc/dd1/structopendnp3_1_1_link_config" ],
    [ "opendnp3::LogEntry", "de/dbc/classopendnp3_1_1_log_entry.html", "de/dbc/classopendnp3_1_1_log_entry" ],
    [ "opendnp3::LogEntryCircularBuffer", "df/d97/classopendnp3_1_1_log_entry_circular_buffer.html", "df/d97/classopendnp3_1_1_log_entry_circular_buffer" ],
    [ "opendnp3::Logger", "db/db4/classopendnp3_1_1_logger.html", "db/db4/classopendnp3_1_1_logger" ],
    [ "opendnp3::LogToFile", "d6/d54/classopendnp3_1_1_log_to_file.html", "d6/d54/classopendnp3_1_1_log_to_file" ],
    [ "opendnp3::LogToStdio", "d8/df6/classopendnp3_1_1_log_to_stdio.html", "d8/df6/classopendnp3_1_1_log_to_stdio" ],
    [ "opendnp3::LogTypes", "d3/d5a/classopendnp3_1_1_log_types.html", "d3/d5a/classopendnp3_1_1_log_types" ],
    [ "opendnp3::MasterConfig", "d7/de1/structopendnp3_1_1_master_config.html", "d7/de1/structopendnp3_1_1_master_config" ],
    [ "opendnp3::MasterStackConfig", "d7/d97/structopendnp3_1_1_master_stack_config.html", "d7/d97/structopendnp3_1_1_master_stack_config" ],
    [ "opendnp3::MaxMinWrapper< T >", "db/d26/structopendnp3_1_1_max_min_wrapper.html", "db/d26/structopendnp3_1_1_max_min_wrapper" ],
    [ "opendnp3::MaxMinWrapper< double >", "de/d81/structopendnp3_1_1_max_min_wrapper_3_01double_01_4.html", "de/d81/structopendnp3_1_1_max_min_wrapper_3_01double_01_4" ],
    [ "opendnp3::NotImplementedException", "d9/d8f/classopendnp3_1_1_not_implemented_exception.html", "d9/d8f/classopendnp3_1_1_not_implemented_exception" ],
    [ "opendnp3::NotSupportedException", "d9/d20/classopendnp3_1_1_not_supported_exception.html", "d9/d20/classopendnp3_1_1_not_supported_exception" ],
    [ "opendnp3::NullDataObserver", "d9/d6d/classopendnp3_1_1_null_data_observer.html", "d9/d6d/classopendnp3_1_1_null_data_observer" ],
    [ "opendnp3::ObjectBase", "dc/d45/classopendnp3_1_1_object_base.html", "dc/d45/classopendnp3_1_1_object_base" ],
    [ "opendnp3::ObjectException", "d3/dcc/classopendnp3_1_1_object_exception.html", "d3/dcc/classopendnp3_1_1_object_exception" ],
    [ "opendnp3::ParameterException", "df/d57/classopendnp3_1_1_parameter_exception.html", "df/d57/classopendnp3_1_1_parameter_exception" ],
    [ "opendnp3::Parsing", "d1/df8/classopendnp3_1_1_parsing.html", "d1/df8/classopendnp3_1_1_parsing" ],
    [ "opendnp3::PlaceHolderObject", "da/d41/classopendnp3_1_1_place_holder_object.html", "da/d41/classopendnp3_1_1_place_holder_object" ],
    [ "opendnp3::PointRecord", "dd/dc8/structopendnp3_1_1_point_record.html", "dd/dc8/structopendnp3_1_1_point_record" ],
    [ "opendnp3::PrintingDataObserver", "d4/df6/classopendnp3_1_1_printing_data_observer.html", "d4/df6/classopendnp3_1_1_printing_data_observer" ],
    [ "opendnp3::QualityConverter< T >", "da/d0e/classopendnp3_1_1_quality_converter.html", "da/d0e/classopendnp3_1_1_quality_converter" ],
    [ "opendnp3::QualityInfo< T, N >", "de/d10/structopendnp3_1_1_quality_info.html", "de/d10/structopendnp3_1_1_quality_info" ],
    [ "opendnp3::ReadTimeoutException", "d9/d40/classopendnp3_1_1_read_timeout_exception.html", "d9/d40/classopendnp3_1_1_read_timeout_exception" ],
    [ "opendnp3::SerialSettings", "d8/d76/structopendnp3_1_1_serial_settings.html", "d8/d76/structopendnp3_1_1_serial_settings" ],
    [ "opendnp3::SetpointStatus", "d7/d24/classopendnp3_1_1_setpoint_status.html", "d7/d24/classopendnp3_1_1_setpoint_status" ],
    [ "opendnp3::SimpleCommandHandler", "da/d39/classopendnp3_1_1_simple_command_handler.html", "da/d39/classopendnp3_1_1_simple_command_handler" ],
    [ "opendnp3::SimpleDataObserver", "dc/db2/classopendnp3_1_1_simple_data_observer.html", "dc/db2/classopendnp3_1_1_simple_data_observer" ],
    [ "opendnp3::SizeByVariationObject", "de/ddc/classopendnp3_1_1_size_by_variation_object.html", "de/ddc/classopendnp3_1_1_size_by_variation_object" ],
    [ "opendnp3::SlaveConfig", "d3/d81/structopendnp3_1_1_slave_config.html", "d3/d81/structopendnp3_1_1_slave_config" ],
    [ "opendnp3::SlaveStackConfig", "d8/d58/structopendnp3_1_1_slave_stack_config.html", "d8/d58/structopendnp3_1_1_slave_stack_config" ],
    [ "opendnp3::StreamObject< T >", "d1/d73/classopendnp3_1_1_stream_object.html", "d1/d73/classopendnp3_1_1_stream_object" ],
    [ "opendnp3::SubjectBase", "d9/dde/classopendnp3_1_1_subject_base.html", "d9/dde/classopendnp3_1_1_subject_base" ],
    [ "opendnp3::SuccessCommandHandler", "d9/dea/classopendnp3_1_1_success_command_handler.html", "d9/dea/classopendnp3_1_1_success_command_handler" ],
    [ "opendnp3::Threadable", "d9/d9d/classopendnp3_1_1_threadable.html", "d9/d9d/classopendnp3_1_1_threadable" ],
    [ "opendnp3::Transaction", "d3/d9a/classopendnp3_1_1_transaction.html", "d3/d9a/classopendnp3_1_1_transaction" ],
    [ "opendnp3::TypedDataPoint< T >", "d6/d5f/classopendnp3_1_1_typed_data_point.html", "d6/d5f/classopendnp3_1_1_typed_data_point" ],
    [ "opendnp3::Uncopyable", "df/d25/classopendnp3_1_1_uncopyable.html", "df/d25/classopendnp3_1_1_uncopyable" ],
    [ "opendnp3::VtoRouterSettings", "df/d69/structopendnp3_1_1_vto_router_settings.html", "df/d69/structopendnp3_1_1_vto_router_settings" ]
];